CREATE TABLE IF NOT EXISTS "college_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "college_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"college_name" varchar(255) NOT NULL,
	"created_by" integer NOT NULL,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "committee_member_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "committee_member_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"committee_id" integer NOT NULL,
	"staff_id" integer,
	"member_name" varchar(150) NOT NULL,
	"designation" varchar(150),
	"member_role" varchar(30) DEFAULT 'MEMBER',
	"sort_order" integer DEFAULT 0,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "committee_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "committee_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	"committee_type" varchar(30) DEFAULT 'ARTS',
	"academic_year" varchar(20),
	"description" text,
	"order_no" varchar(100),
	"order_date" date,
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dashboard_card_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboard_card_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"card_key" varchar(50) NOT NULL,
	"card_content_id" varchar(50) NOT NULL,
	"card_title" varchar(100) NOT NULL,
	"card_subtitle" varchar(100),
	"card_icon" varchar(50) DEFAULT 'bi-card-text',
	"card_color" varchar(30) DEFAULT 'primary',
	"card_url" varchar(255),
	"card_order" integer DEFAULT 0,
	"card_category" varchar(50) DEFAULT 'general',
	"menu_id" integer DEFAULT 0 NOT NULL,
	"data_source" varchar(255),
	"display" char(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daybook_item_category_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daybook_item_category_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	"item_type_id" integer NOT NULL,
	"display" varchar(1) DEFAULT 'Y' NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daybook_item_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daybook_item_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"daybook_id" integer NOT NULL,
	"sl_no" integer DEFAULT 1 NOT NULL,
	"transaction_type" varchar(10) DEFAULT 'RECEIPT' NOT NULL,
	"item_id" integer NOT NULL,
	"item_description" varchar(300) NOT NULL,
	"item_type_id" integer,
	"item_category_id" integer,
	"unit_id" integer,
	"issued_to_id" integer,
	"receipt_qty_number" numeric(12, 3) DEFAULT '0',
	"receipt_qty_weight" numeric(12, 3) DEFAULT '0',
	"issue_qty_number" numeric(12, 3) DEFAULT '0',
	"issue_qty_weight" numeric(12, 3) DEFAULT '0',
	"balance_qty_number" numeric(12, 3) DEFAULT '0',
	"balance_qty_weight" numeric(12, 3) DEFAULT '0',
	"receipt_rate" numeric(12, 2) DEFAULT '0',
	"receipt_amount_rs" numeric(12, 2) DEFAULT '0',
	"receipt_amount_ps" numeric(6, 2) DEFAULT '0',
	"issue_rate" numeric(12, 2) DEFAULT '0',
	"issue_amount_rs" numeric(12, 2) DEFAULT '0',
	"issue_amount_ps" numeric(6, 2) DEFAULT '0',
	"balance_rate" numeric(12, 2) DEFAULT '0',
	"balance_amount_rs" numeric(12, 2) DEFAULT '0',
	"balance_amount_ps" numeric(6, 2) DEFAULT '0',
	"value_verifier" varchar(50),
	"indent_no" varchar(100),
	"indent_date" date,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daybook_item_type_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daybook_item_type_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"display" varchar(1) DEFAULT 'Y' NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daybook_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daybook_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"page_no" varchar(20) NOT NULL,
	"stockbook_type_id" integer NOT NULL,
	"institution_id" integer,
	"department_id" integer,
	"class" varchar(100),
	"unit_label" varchar(100),
	"receipt_order_no" varchar(100),
	"document_date" date NOT NULL,
	"service_provider_id" integer NOT NULL,
	"invoice_ref" varchar(150),
	"invoice_date" date,
	"indent_no" varchar(100),
	"indent_date" date,
	"issued_to" varchar(150),
	"cr_voucher_ref" varchar(100),
	"verifier_id" integer,
	"remarks" text,
	"status" varchar(20) DEFAULT 'ACTIVE' NOT NULL,
	"created_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"issued_to_id" integer,
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daybook_unit_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daybook_unit_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"display" varchar(1) DEFAULT 'Y' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "department_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "department_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"college_id" integer DEFAULT 1 NOT NULL,
	"department_name" varchar(100) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "designation_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "designation_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"designation_name" varchar(150) NOT NULL,
	"staff_type" varchar(20) DEFAULT 'TEACHING',
	"staff_category" varchar(20) DEFAULT 'FACULTY',
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "document_remark_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_remark_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"document_id" integer NOT NULL,
	"remark_date" date,
	"remark" text NOT NULL,
	"created_by" integer,
	"created_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "document_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"doc_type" varchar(30) DEFAULT 'custom',
	"body" text,
	"place" varchar(150),
	"doc_date" date,
	"submitted_name" varchar(150),
	"designation" varchar(150),
	"department" varchar(255),
	"institution" varchar(255),
	"signed_by" integer,
	"status" varchar(20) DEFAULT 'DRAFT',
	"attachment_path" varchar(255),
	"attachment_name" varchar(255),
	"attachment_type" varchar(100),
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_duty_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_duty_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item_id" integer NOT NULL,
	"staff_id" integer,
	"person_name" varchar(150) NOT NULL,
	"duty_role" varchar(20) DEFAULT 'JUDGE',
	"sort_order" integer DEFAULT 0,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_item_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_item_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"name" varchar(150) NOT NULL,
	"category" varchar(20) DEFAULT 'ON_STAGE',
	"item_type" varchar(20) DEFAULT 'SINGLE',
	"stage" varchar(100),
	"venue" varchar(150),
	"scheduled_date" date,
	"scheduled_time" varchar(40),
	"topic" varchar(255),
	"sort_order" integer DEFAULT 0,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_participant_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_participant_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item_id" integer NOT NULL,
	"chest_no" varchar(20),
	"participant_name" varchar(150) NOT NULL,
	"class_name" varchar(50),
	"phone" varchar(20),
	"parent_name" varchar(150),
	"parent_phone" varchar(20),
	"judge1_score" numeric(6, 2),
	"judge2_score" numeric(6, 2),
	"judge3_score" numeric(6, 2),
	"average_score" numeric(6, 2),
	"grade" varchar(10),
	"place" integer,
	"remarks" varchar(255),
	"sort_order" integer DEFAULT 0,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"committee_id" integer,
	"name" varchar(150) NOT NULL,
	"subtitle" varchar(200),
	"academic_year" varchar(20),
	"start_date" date,
	"end_date" date,
	"venue" varchar(255),
	"adviser_name" varchar(150),
	"principal_name" varchar(150),
	"status" varchar(20) DEFAULT 'OPEN',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "group_item_name_master_t" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "group_item_name_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_name" varchar(255) NOT NULL,
	"group_code" varchar(50),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "indent_item_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "indent_item_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"indent_id" integer NOT NULL,
	"sl_no" integer NOT NULL,
	"item_id" integer NOT NULL,
	"group_id" integer,
	"make_id" integer,
	"model_id" integer,
	"item_description" varchar(1000),
	"item_purpose" varchar(255),
	"qty_intended" integer NOT NULL,
	"qty_passed" integer DEFAULT 0,
	"qty_issued" integer DEFAULT 0,
	"remarks" varchar(255),
	"stock_book_page_no" integer,
	"stock_book_volume" integer,
	"day_book_page_no" integer,
	"day_book_volume" integer,
	"display" varchar(1) DEFAULT 'Y',
	"status_id" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "indent_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "indent_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"department_id" integer DEFAULT 1 NOT NULL,
	"institution_id" integer DEFAULT 1 NOT NULL,
	"book_no" integer NOT NULL,
	"indent_no" varchar(50) NOT NULL,
	"indent_date" date NOT NULL,
	"purpose" text,
	"item_type" varchar(1) DEFAULT 'N',
	"created_by" integer NOT NULL,
	"verified_by" integer,
	"passed_by" integer,
	"issued_by" integer,
	"received_by" integer,
	"status" varchar(20) DEFAULT 'CREATED',
	"bill_path" varchar(255),
	"bill_name" varchar(255),
	"bill_type" varchar(100),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "issued_to_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issued_to_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"location_code" varchar(50) NOT NULL,
	"location_name" varchar(255) NOT NULL,
	"description" text,
	"contact_person" varchar(100),
	"phone" varchar(20),
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "item_group_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "item_group_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_name" varchar(255) NOT NULL,
	"description" text,
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "item_group_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "item_group_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_name" varchar(150) NOT NULL,
	"group_code" varchar(50),
	"description" text,
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer NOT NULL,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "item_master_t" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "item_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"item_name" varchar(255) NOT NULL,
	"item_code" varchar(50),
	"group_id" bigint,
	"category_id" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y',
	"tax_not_tax" varchar(1) DEFAULT 'N' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "kfc_form_13_item_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kfc_form_13_item_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"form_id" integer NOT NULL,
	"sl_no" integer NOT NULL,
	"item_id" integer,
	"article" text,
	"stock_on_hand" integer DEFAULT 0,
	"purchase_year" integer DEFAULT 0,
	"qty_required" integer DEFAULT 0,
	"rate_unit" integer DEFAULT 0,
	"rate_amount" integer DEFAULT 0,
	"supplier" varchar(255),
	"purpose" text,
	"delivery_place" varchar(255),
	"classification_no" varchar(100),
	"remarks" varchar(500),
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "kfc_form_13_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kfc_form_13_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"form_date" date,
	"department_id" integer,
	"signed_by" integer,
	"signatory_name" varchar(150),
	"signatory_designation" varchar(150),
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "kfc_form_21_item_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kfc_form_21_item_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"form_id" integer NOT NULL,
	"sl_no" integer NOT NULL,
	"item_id" integer,
	"quantity" integer DEFAULT 0,
	"description" text,
	"book_rate" numeric(12, 2) DEFAULT '0',
	"book_amount" numeric(12, 2) DEFAULT '0',
	"assessed_value" numeric(12, 2) DEFAULT '0',
	"date_of_receipt" date,
	"cause_remarks" text,
	"authority_remarks" text,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "kfc_form_21_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kfc_form_21_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"form_date" date,
	"department_id" integer,
	"signed_by" integer,
	"signatory_name" varchar(150),
	"signatory_designation" varchar(150),
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "language_translation_t" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "language_translation_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"label" varchar(255) NOT NULL,
	"english" text,
	"french" text,
	"module_id" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "licenses_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "licenses_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"license_number" varchar(50) NOT NULL,
	"bank_id" integer,
	"client_id" integer NOT NULL,
	"license_cleared_by" integer,
	"entry_post_id" integer,
	"ref_cod" varchar(50),
	"type_of_goods_id" integer NOT NULL,
	"weight" numeric(10, 2),
	"m3" numeric(10, 2),
	"unit_of_measurement_id" integer,
	"fob_declared" numeric(15, 2),
	"insurance" numeric(15, 2),
	"freight" numeric(15, 2),
	"other_costs" numeric(15, 2),
	"transport_mode_id" integer NOT NULL,
	"invoice_number" varchar(50),
	"invoice_file" varchar(255),
	"invoice_date" date,
	"currency_id" integer NOT NULL,
	"supplier" varchar(255),
	"license_applied_date" date,
	"license_validation_date" date,
	"license_expiry_date" date,
	"license_file" varchar(255),
	"kind_id" integer,
	"payment_method_id" integer,
	"payment_subtype_id" integer,
	"destination_id" integer,
	"fsi" varchar(100),
	"aur" varchar(100),
	"status" varchar(20) DEFAULT 'ACTIVE',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"display" varchar(1) DEFAULT 'Y' NOT NULL,
	"fob_currency_id" integer DEFAULT 1,
	"insurance_currency_id" integer DEFAULT 1,
	"freight_currency_id" integer DEFAULT 1,
	"other_costs_currency_id" integer DEFAULT 1
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "locals_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "locals_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"location" integer NOT NULL,
	"mca_lt_reference" varchar(100) NOT NULL,
	"lot_num" varchar(100),
	"horse" varchar(100),
	"trailer_1" varchar(100),
	"trailer_2" varchar(100),
	"transporter" varchar(100),
	"nbr_of_bags" integer,
	"weight" numeric(10, 2),
	"arrival_date" date,
	"loading_date" date,
	"bp_details_received_date" date,
	"pv_div_mines_date" date,
	"demande_attestation_date" date,
	"ceec_in" date,
	"ceec_out" date,
	"cgea" varchar(100),
	"gov_docs_complete_date" date,
	"disp_date" date,
	"end_of_formalities" date,
	"remarks" text,
	"display" varchar(1) DEFAULT 'Y' NOT NULL,
	"created_by" integer DEFAULT 1 NOT NULL,
	"updated_by" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "make_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "make_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"make_name" varchar(255) NOT NULL,
	"created_by" integer NOT NULL,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "menu_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "menu_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"menu_id" integer,
	"menu_order" integer DEFAULT 1 NOT NULL,
	"menu_level" integer,
	"menu_name" varchar(255),
	"url" varchar(255),
	"text" varchar(100),
	"icon" varchar(100) DEFAULT '  ',
	"badge" varchar(50) DEFAULT '  ',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "model_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "model_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"make_id" integer NOT NULL,
	"model_name" varchar(255) NOT NULL,
	"created_by" integer NOT NULL,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "qualification_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qualification_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"qualification_name" varchar(150) NOT NULL,
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quotation_categories_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quotation_categories_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category_name" varchar(100) NOT NULL,
	"category_header" varchar(255) NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"display" varchar(1) DEFAULT 'Y',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_dashboard_card_mapping_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_dashboard_card_mapping_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_id" integer NOT NULL,
	"card_id" integer NOT NULL,
	"menu_id" integer DEFAULT 0 NOT NULL,
	"is_visible" integer DEFAULT 1,
	"card_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_name" varchar(100) NOT NULL,
	"department_id" integer,
	"office_location_id" integer,
	"parent_role_id" integer,
	"approval_level" integer,
	"department" integer DEFAULT 0,
	"management" integer DEFAULT 0,
	"finance" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"display" varchar(1) DEFAULT 'Y',
	"level" numeric(10, 2)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_menu_mapping_t" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_menu_mapping_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role_id" bigint NOT NULL,
	"menu_id" bigint NOT NULL,
	"can_view" integer DEFAULT 0,
	"can_add" integer DEFAULT 0,
	"can_edit" integer DEFAULT 0,
	"can_delete" integer DEFAULT 0,
	"can_approve" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"created_by" bigint,
	"updated_by" bigint
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "service_providers_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_providers_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider_name" varchar(255) NOT NULL,
	"type" varchar(10) NOT NULL,
	"phone_no" varchar(20) NOT NULL,
	"email" varchar(255) NOT NULL,
	"gst_no" varchar(15),
	"address" text NOT NULL,
	"created_by" integer NOT NULL,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "staff_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "staff_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"staff_code" varchar(50),
	"staff_name" varchar(255) NOT NULL,
	"designation" varchar(150),
	"department_id" integer,
	"staff_type" varchar(20) DEFAULT 'TEACHING',
	"staff_category" varchar(20) DEFAULT 'FACULTY',
	"posting_type" varchar(20) DEFAULT 'PERMANENT',
	"qualification" varchar(255),
	"subjects" text,
	"max_periods_per_week" integer DEFAULT 0,
	"email" varchar(150),
	"phone" varchar(20),
	"gender" varchar(10),
	"date_of_joining" date,
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "status_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "status_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"status_name" varchar(100) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"created_by" integer,
	"updated_at" timestamp,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_book_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_book_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item_id" integer NOT NULL,
	"location" varchar(100) NOT NULL,
	"location_id" integer DEFAULT 1 NOT NULL,
	"opening_balance" integer DEFAULT 0,
	"current_balance" integer DEFAULT 0,
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y',
	"serial_tracking_enabled" varchar(1) DEFAULT 'N'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_entry_batch_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_entry_batch_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"batch_code" varchar(100) NOT NULL,
	"entry_type" varchar(20) NOT NULL,
	"batch_status" varchar(20) DEFAULT 'DRAFT',
	"item_count" integer DEFAULT 0,
	"total_quantity" integer DEFAULT 0,
	"batch_date" date NOT NULL,
	"notes" text,
	"created_by" integer NOT NULL,
	"verified_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_entry_log_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_entry_log_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stock_transaction_id" integer NOT NULL,
	"action" varchar(50) NOT NULL,
	"old_values" text,
	"new_values" text,
	"action_by" integer NOT NULL,
	"action_reason" text,
	"created_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_serial_tracking_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_serial_tracking_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stock_transaction_id" integer NOT NULL,
	"stock_book_id" integer NOT NULL,
	"serial_no" varchar(100) NOT NULL,
	"item_status" varchar(20) DEFAULT 'WORKING',
	"issued_to_location_id" integer,
	"issued_date" date,
	"issue_remarks" text,
	"created_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_transaction_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_transaction_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"institution_id" integer DEFAULT 1 NOT NULL,
	"department_id" integer DEFAULT 1 NOT NULL,
	"stock_book_id" integer NOT NULL,
	"transaction_date" date NOT NULL,
	"transaction_type" varchar(20) NOT NULL,
	"stock_entry_type" varchar(20) DEFAULT 'INDENT_BASED',
	"item_type" varchar(20) DEFAULT 'CONSUMABLE',
	"item_category" varchar(100),
	"book_volume" integer DEFAULT 1,
	"voucher_no" varchar(50),
	"voucher_date" date,
	"indent_id" integer,
	"indent_item_id" integer,
	"group_item_id" integer,
	"transfer_item_id" bigint,
	"received_from" varchar(200),
	"issued_to" varchar(200),
	"issued_to_location_id" integer,
	"transferred_from_location_id" integer,
	"receipt_qty" integer DEFAULT 0,
	"issue_qty" integer DEFAULT 0,
	"balance_qty" integer NOT NULL,
	"brought_forward" integer DEFAULT 0,
	"carried_over" integer DEFAULT 0,
	"item_status" varchar(20) DEFAULT 'WORKING',
	"make" varchar(100),
	"model" varchar(100),
	"description" text,
	"serial_no" varchar(100),
	"receiver_initial" varchar(100),
	"remarks" text,
	"batch_code" varchar(200),
	"verification_status" varchar(20) DEFAULT 'PENDING',
	"verified_by" integer,
	"verified_at" timestamp,
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_transfer_detail_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_transfer_detail_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stock_transaction_id" integer NOT NULL,
	"source_location_id" integer NOT NULL,
	"destination_location_id" integer NOT NULL,
	"quantity_transferred" integer NOT NULL,
	"condition_status" varchar(50) DEFAULT 'GOOD',
	"transfer_reason" text,
	"created_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stockbook_type_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stockbook_type_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(20) NOT NULL,
	"display" varchar(1) DEFAULT 'Y' NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "subject_faculty_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subject_faculty_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"subject_id" integer NOT NULL,
	"staff_id" integer NOT NULL,
	"created_by" integer,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "subject_master_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subject_master_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"subject_code" varchar(50),
	"subject_name" varchar(255) NOT NULL,
	"department_id" integer,
	"semester" varchar(20),
	"scheme" varchar(40),
	"course_category" varchar(120),
	"subject_type" varchar(20) DEFAULT 'THEORY',
	"lecture_hours" integer DEFAULT 0,
	"tutorial_hours" integer DEFAULT 0,
	"practical_hours" integer DEFAULT 0,
	"credits" numeric(4, 1),
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "timetable_period_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timetable_period_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timetable_id" integer NOT NULL,
	"period_no" integer NOT NULL,
	"label" varchar(50),
	"start_time" varchar(10),
	"end_time" varchar(10),
	"fri_start_time" varchar(10),
	"fri_end_time" varchar(10),
	"is_break" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "timetable_slot_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timetable_slot_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timetable_id" integer NOT NULL,
	"day" varchar(3) NOT NULL,
	"period_no" integer NOT NULL,
	"subject_id" integer,
	"staff_id" integer,
	"batch" varchar(50),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "timetable_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timetable_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"department_id" integer,
	"semester" varchar(20),
	"scheme" varchar(40),
	"academic_year" varchar(20),
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"email" varchar(100) NOT NULL,
	"mobile" varchar(15),
	"full_name" varchar(255) NOT NULL,
	"role_id" integer NOT NULL,
	"display" varchar(1) DEFAULT 'Y',
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"profile_image" varchar(255) DEFAULT 'default.jpg',
	"signature_image" varchar(150),
	"location_id" varchar(100),
	"dept_id" varchar(100)
);
