CREATE TABLE IF NOT EXISTS "attachment_t" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attachment_t_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_type" varchar(20) NOT NULL,
	"owner_id" integer NOT NULL,
	"category" varchar(30) DEFAULT 'OTHER',
	"title" varchar(255),
	"file_path" varchar(255) NOT NULL,
	"file_name" varchar(255),
	"file_type" varchar(100),
	"file_size" integer,
	"uploaded_by" integer,
	"created_at" timestamp DEFAULT now(),
	"display" varchar(1) DEFAULT 'Y'
);
--> statement-breakpoint
ALTER TABLE "committee_t" DROP COLUMN IF EXISTS "order_path";--> statement-breakpoint
ALTER TABLE "committee_t" DROP COLUMN IF EXISTS "order_name";--> statement-breakpoint
ALTER TABLE "committee_t" DROP COLUMN IF EXISTS "order_type";