/**
 * Create qualification_master_t, seed essential qualifications, and add a
 * "Qualification" menu entry under Masters. Additive & idempotent.
 * Usage: npx tsx scripts/create-qualification-table.ts
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url = process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";
const sql = postgres(url, { max: 1 });

const SEED = [
  "SSLC",
  "Higher Secondary (Plus Two)",
  "ITI",
  "Diploma",
  "B.Sc",
  "B.E / B.Tech",
  "BCA",
  "M.Sc",
  "M.E / M.Tech",
  "MCA",
  "MBA",
  "B.Ed",
  "Ph.D",
];

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS qualification_master_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      qualification_name varchar(150) NOT NULL,
      display varchar(1) DEFAULT 'Y',
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now()
    )`;
  await sql`CREATE UNIQUE INDEX IF NOT EXISTS qualification_name_uniq ON qualification_master_t (qualification_name)`;
  console.log("✔ qualification_master_t is ready.");

  let added = 0;
  for (const name of SEED) {
    const r = await sql`
      INSERT INTO qualification_master_t (qualification_name, display)
      VALUES (${name}, 'Y')
      ON CONFLICT (qualification_name) DO NOTHING
      RETURNING id`;
    if (r.length) added++;
  }
  console.log(`✔ Seeded ${added} qualification(s).`);

  try {
    const existing = await sql`SELECT id FROM menu_master_t WHERE url = 'qualification' LIMIT 1`;
    if (existing.length === 0) {
      const parent = await sql`
        SELECT id FROM menu_master_t
        WHERE menu_level = 0 AND (text ILIKE 'Masters' OR menu_name ILIKE 'Masters') LIMIT 1`;
      const parentId = parent[0]?.id ?? null;
      const next = await sql`SELECT COALESCE(MAX(id),0)+1 AS id FROM menu_master_t`;
      if (parentId) {
        await sql`
          INSERT INTO menu_master_t (id, menu_id, menu_order, menu_level, menu_name, url, text, icon, display)
          VALUES (${next[0].id}, ${parentId}, 44, 1, 'Qualification', 'qualification', 'Qualification', 'ti ti-certificate', 'Y')`;
        console.log("✔ Added 'Qualification' menu entry under Masters.");
      }
    }
  } catch (e) {
    console.log("• Skipped menu insert:", (e as Error).message);
  }

  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
