/**
 * Create the staff_t table + add a "Staff" menu entry under Masters (additive,
 * idempotent). Usage: npx tsx scripts/create-staff-table.ts
 * Mirrors staffT in src/db/schema.ts.
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url = process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";
const sql = postgres(url, { max: 1 });

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS staff_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      staff_code varchar(50),
      staff_name varchar(255) NOT NULL,
      designation varchar(150),
      department_id integer,
      staff_type varchar(20) DEFAULT 'TEACHING',
      qualification varchar(255),
      subjects text,
      max_periods_per_week integer DEFAULT 0,
      email varchar(150),
      phone varchar(20),
      gender varchar(10),
      date_of_joining date,
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now(),
      display varchar(1) DEFAULT 'Y'
    )
  `;
  console.log("✔ staff_t is ready.");

  // Surface it in the sidebar under the Masters group.
  try {
    const existing = await sql`SELECT id FROM menu_master_t WHERE url = 'staff' LIMIT 1`;
    if (existing.length === 0) {
      const parent = await sql`
        SELECT id FROM menu_master_t
        WHERE menu_level = 0 AND (text ILIKE 'Masters' OR menu_name ILIKE 'Masters')
        LIMIT 1`;
      const parentId = parent[0]?.id ?? null;
      const next = await sql`SELECT COALESCE(MAX(id),0)+1 AS id FROM menu_master_t`;
      if (parentId) {
        await sql`
          INSERT INTO menu_master_t (id, menu_id, menu_order, menu_level, menu_name, url, text, icon, display)
          VALUES (${next[0].id}, ${parentId}, 40, 1, 'Staff', 'staff', 'Staff', 'ti ti-users', 'Y')`;
        console.log("✔ Added 'Staff' menu entry under Masters.");
      } else {
        console.log("• No Masters parent menu found — add a 'Staff' menu row manually if you want it in the sidebar.");
      }
    }
  } catch (e) {
    console.log("• Skipped menu insert:", (e as Error).message);
  }

  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
