/**
 * Surgically create the document_t table (additive; safe on existing data).
 * Usage: npx tsx scripts/create-document-table.ts
 * Mirrors documentT in src/db/schema.ts. Idempotent (IF NOT EXISTS).
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url =
  process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";
const sql = postgres(url, { max: 1 });

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS document_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title varchar(255) NOT NULL,
      doc_type varchar(30) DEFAULT 'custom',
      body text,
      place varchar(150),
      doc_date date,
      submitted_name varchar(150),
      designation varchar(150),
      department varchar(255),
      institution varchar(255),
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now(),
      display varchar(1) DEFAULT 'Y'
    )
  `;
  console.log("✔ document_t is ready.");
  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
