/**
 * Surgically create the K.F.C. Form 13 tables (additive; safe on existing data).
 * Usage: npx tsx scripts/create-kfc-tables.ts
 *
 * Mirrors kfcForm13T / kfcForm13ItemT in src/db/schema.ts. Uses IF NOT EXISTS so
 * it is idempotent and never alters/drops the migrated tables.
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url =
  process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";

const sql = postgres(url, { max: 1 });

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS kfc_form_13_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title varchar(255) NOT NULL,
      form_date date,
      department_id integer,
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now(),
      display varchar(1) DEFAULT 'Y'
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS kfc_form_13_item_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      form_id integer NOT NULL,
      sl_no integer NOT NULL,
      item_id integer,
      article text,
      stock_on_hand integer DEFAULT 0,
      purchase_year integer DEFAULT 0,
      qty_required integer DEFAULT 0,
      rate_unit integer DEFAULT 0,
      rate_amount integer DEFAULT 0,
      supplier varchar(255),
      purpose text,
      delivery_place varchar(255),
      classification_no varchar(100),
      remarks varchar(500),
      display varchar(1) DEFAULT 'Y',
      created_at timestamp DEFAULT now()
    )
  `;

  // Helps the list/edit joins that filter rows by their parent form.
  await sql`CREATE INDEX IF NOT EXISTS kfc_form_13_item_form_id_idx ON kfc_form_13_item_t (form_id)`;

  console.log("✔ kfc_form_13_t and kfc_form_13_item_t are ready.");
  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
