/**
 * Create subject_master_t + subject_faculty_t, ensure the "faculty" designations
 * (Tradesman / Trade Instructor) count as TEACHING, and add menu entries.
 * Additive & idempotent.  Usage: npx tsx scripts/create-subject-mapping.ts
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url = process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";
const sql = postgres(url, { max: 1 });

async function addMenu(urlSlug: string, label: string, order: number, icon: string) {
  const existing = await sql`SELECT id FROM menu_master_t WHERE url = ${urlSlug} LIMIT 1`;
  if (existing.length) return;
  const parent = await sql`
    SELECT id FROM menu_master_t
    WHERE menu_level = 0 AND (text ILIKE 'Masters' OR menu_name ILIKE 'Masters') LIMIT 1`;
  const parentId = parent[0]?.id ?? null;
  const next = await sql`SELECT COALESCE(MAX(id),0)+1 AS id FROM menu_master_t`;
  if (parentId) {
    await sql`
      INSERT INTO menu_master_t (id, menu_id, menu_order, menu_level, menu_name, url, text, icon, display)
      VALUES (${next[0].id}, ${parentId}, ${order}, 1, ${label}, ${urlSlug}, ${label}, ${icon}, 'Y')`;
    console.log(`✔ Added '${label}' menu entry.`);
  } else {
    console.log(`• No Masters parent — add '${label}' menu row manually.`);
  }
}

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS subject_master_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      subject_code varchar(50),
      subject_name varchar(255) NOT NULL,
      department_id integer,
      semester varchar(20),
      subject_type varchar(20) DEFAULT 'THEORY',
      display varchar(1) DEFAULT 'Y',
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now()
    )`;
  console.log("✔ subject_master_t is ready.");

  await sql`
    CREATE TABLE IF NOT EXISTS subject_faculty_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      subject_id integer NOT NULL,
      staff_id integer NOT NULL,
      created_by integer,
      created_at timestamp DEFAULT now()
    )`;
  await sql`CREATE UNIQUE INDEX IF NOT EXISTS subject_faculty_uniq ON subject_faculty_t (subject_id, staff_id)`;
  console.log("✔ subject_faculty_t is ready.");

  // Make the workshop trades count as teaching faculty (per requirement).
  await sql`UPDATE designation_master_t SET staff_type='TEACHING' WHERE designation_name IN ('Tradesman')`;
  await sql`
    INSERT INTO designation_master_t (designation_name, staff_type, staff_category, display)
    VALUES ('Trade Instructor', 'TEACHING', 'FACULTY', 'Y')
    ON CONFLICT (designation_name) DO UPDATE SET staff_type='TEACHING'`;
  console.log("✔ Tradesman / Trade Instructor set as TEACHING faculty.");

  await addMenu("subject", "Subject", 42, "ti ti-book");
  await addMenu("subject-faculty", "Subject–Faculty Map", 43, "ti ti-link");

  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
