/**
 * Create designation_master_t + a "Designation" menu entry under Masters, and
 * seed a few common designations. Additive & idempotent.
 * Usage: npx tsx scripts/create-designation-table.ts
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url = process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";
const sql = postgres(url, { max: 1 });

const SEED = [
  "Principal",
  "Head of Department",
  "Lecturer",
  "Senior Lecturer",
  "Workshop Instructor",
  "Instructor / Demonstrator",
  "Tradesman",
  "Lab Assistant",
  "Office Superintendent",
  "Clerk",
  "Attender",
];

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS designation_master_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      designation_name varchar(150) NOT NULL,
      display varchar(1) DEFAULT 'Y',
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now()
    )
  `;
  await sql`CREATE UNIQUE INDEX IF NOT EXISTS designation_name_uniq ON designation_master_t (designation_name)`;
  console.log("✔ designation_master_t is ready.");

  // Seed common designations (skip any that already exist).
  let added = 0;
  for (const name of SEED) {
    const r = await sql`
      INSERT INTO designation_master_t (designation_name, display)
      VALUES (${name}, 'Y')
      ON CONFLICT (designation_name) DO NOTHING
      RETURNING id`;
    if (r.length) added++;
  }
  console.log(`✔ Seeded ${added} designation(s).`);

  // Menu entry under Masters.
  try {
    const existing = await sql`SELECT id FROM menu_master_t WHERE url = 'designation' LIMIT 1`;
    if (existing.length === 0) {
      const parent = await sql`
        SELECT id FROM menu_master_t
        WHERE menu_level = 0 AND (text ILIKE 'Masters' OR menu_name ILIKE 'Masters')
        LIMIT 1`;
      const parentId = parent[0]?.id ?? null;
      const next = await sql`SELECT COALESCE(MAX(id),0)+1 AS id FROM menu_master_t`;
      if (parentId) {
        await sql`
          INSERT INTO menu_master_t (id, menu_id, menu_order, menu_level, menu_name, url, text, icon, display)
          VALUES (${next[0].id}, ${parentId}, 41, 1, 'Designation', 'designation', 'Designation', 'ti ti-badge', 'Y')`;
        console.log("✔ Added 'Designation' menu entry under Masters.");
      } else {
        console.log("• No Masters parent menu found — add a 'Designation' menu row manually if needed.");
      }
    }
  } catch (e) {
    console.log("• Skipped menu insert:", (e as Error).message);
  }

  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
