/**
 * Surgically create the K.F.C. Form 21 tables (additive; safe on existing data).
 * Usage: npx tsx scripts/create-kfc21-tables.ts
 *
 * Mirrors kfcForm21T / kfcForm21ItemT in src/db/schema.ts. Uses IF NOT EXISTS so
 * it is idempotent and never alters/drops existing tables.
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url =
  process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";

const sql = postgres(url, { max: 1 });

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS kfc_form_21_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title varchar(255) NOT NULL,
      form_date date,
      department_id integer,
      signed_by integer,
      signatory_name varchar(150),
      signatory_designation varchar(150),
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now(),
      display varchar(1) DEFAULT 'Y'
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS kfc_form_21_item_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      form_id integer NOT NULL,
      sl_no integer NOT NULL,
      item_id integer,
      quantity integer DEFAULT 0,
      description text,
      book_rate numeric(12,2) DEFAULT 0,
      book_amount numeric(12,2) DEFAULT 0,
      assessed_value numeric(12,2) DEFAULT 0,
      date_of_receipt date,
      cause_remarks text,
      authority_remarks text,
      display varchar(1) DEFAULT 'Y',
      created_at timestamp DEFAULT now()
    )
  `;

  await sql`CREATE INDEX IF NOT EXISTS kfc_form_21_item_form_id_idx ON kfc_form_21_item_t (form_id)`;

  // Best-effort: surface it in the sidebar by adding a menu row next to the
  // other report entries. Skipped silently if the menu table/columns differ.
  try {
    const existing = await sql`SELECT id FROM menu_master_t WHERE url = 'report/kfc-form-21' LIMIT 1`;
    if (existing.length === 0) {
      // Place it under the same parent as an existing report menu, if any.
      const parent = await sql`
        SELECT menu_id FROM menu_master_t
        WHERE url IN ('book','live','custom','report/kfc-form-13') AND menu_level = 1
        LIMIT 1
      `;
      const parentId = parent[0]?.menu_id ?? null;
      const nextId = await sql`SELECT COALESCE(MAX(id),0)+1 AS id FROM menu_master_t`;
      if (parentId) {
        await sql`
          INSERT INTO menu_master_t (id, menu_id, menu_order, menu_level, menu_name, url, text, display)
          VALUES (${nextId[0].id}, ${parentId}, 90, 1, 'KFC Form 21', 'report/kfc-form-21', 'KFC Form 21', 'Y')
        `;
        console.log("✔ Added 'KFC Form 21' menu entry.");
      } else {
        console.log("• No report parent menu found — add a menu row manually if you want it in the sidebar.");
      }
    }
  } catch (e) {
    console.log("• Skipped menu insert:", (e as Error).message);
  }

  console.log("✔ kfc_form_21_t and kfc_form_21_item_t are ready.");
  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
