/**
 * Create the timetable tables + a top-level "Timetable" menu. Additive & idempotent.
 * Usage: npx tsx scripts/create-timetable-tables.ts
 */
import postgres from "postgres";
import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

const url = process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/stock_db";
const sql = postgres(url, { max: 1 });

async function main() {
  await sql`
    CREATE TABLE IF NOT EXISTS timetable_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title varchar(255) NOT NULL,
      department_id integer,
      semester varchar(20),
      scheme varchar(40),
      academic_year varchar(20),
      display varchar(1) DEFAULT 'Y',
      created_by integer,
      updated_by integer,
      created_at timestamp DEFAULT now(),
      updated_at timestamp DEFAULT now()
    )`;
  await sql`
    CREATE TABLE IF NOT EXISTS timetable_period_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      timetable_id integer NOT NULL,
      period_no integer NOT NULL,
      label varchar(50),
      start_time varchar(10),
      end_time varchar(10),
      is_break integer DEFAULT 0
    )`;
  await sql`
    CREATE TABLE IF NOT EXISTS timetable_slot_t (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      timetable_id integer NOT NULL,
      day varchar(3) NOT NULL,
      period_no integer NOT NULL,
      subject_id integer,
      staff_id integer,
      batch varchar(50),
      display varchar(1) DEFAULT 'Y'
    )`;
  await sql`CREATE INDEX IF NOT EXISTS timetable_period_tt_idx ON timetable_period_t (timetable_id)`;
  await sql`CREATE INDEX IF NOT EXISTS timetable_slot_tt_idx ON timetable_slot_t (timetable_id)`;
  console.log("✔ timetable tables are ready.");

  try {
    const existing = await sql`SELECT id FROM menu_master_t WHERE url = 'timetable' LIMIT 1`;
    if (existing.length === 0) {
      const next = await sql`SELECT COALESCE(MAX(id),0)+1 AS id FROM menu_master_t`;
      const id = next[0].id;
      // Top-level menu (menu_level 0).
      await sql`
        INSERT INTO menu_master_t (id, menu_id, menu_order, menu_level, menu_name, url, text, icon, display)
        VALUES (${id}, ${id}, 6, 0, 'Timetable', 'timetable', 'Timetable', 'ti ti-calendar', 'Y')`;
      console.log("✔ Added top-level 'Timetable' menu entry.");
    }
  } catch (e) {
    console.log("• Skipped menu insert:", (e as Error).message);
  }

  await sql.end();
}

main().catch(async (e) => {
  console.error("✖ Failed:", e.message);
  await sql.end();
  process.exit(1);
});
