#!/usr/bin/env node
/**
 * mysql-to-pg.mjs
 * ----------------
 * Converts the original MariaDB/MySQL `stock_db` dump (INSERT statements only)
 * into a PostgreSQL-loadable, data-only SQL file.
 *
 * It does NOT create tables — run the Drizzle migration first
 * (`npm run db:push` or `npm run db:migrate`) so the schema exists, then load
 * the generated file with `npm run db:load` (or psql -f pg_seed.sql).
 *
 * Usage:
 *   node scripts/mysql-to-pg.mjs <input.sql> [output.sql]
 *   # defaults: input = ./stock_db.sql   output = ./pg_seed.sql
 *
 * What it does:
 *   - keeps only INSERT INTO ... ; statements (multi-line aware)
 *   - `identifier`  -> "identifier"   (MySQL backticks -> PG double quotes)
 *   - unescapes MySQL backslash escapes to PG standard-conforming strings
 *   - '0000-00-00' dates -> NULL
 *   - wraps everything in a transaction with session_replication_role=replica
 *     (so any FK/trigger ordering is ignored during bulk load)
 *   - appends setval() calls to fix identity sequences for every touched table
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const input = process.argv[2] ?? "./stock_db.sql";
const output = process.argv[3] ?? "./pg_seed.sql";

if (!existsSync(input)) {
  console.error(
    `\n✖ Input dump not found: ${input}\n` +
      `  Place your MySQL dump there, or pass a path:\n` +
      `    node scripts/mysql-to-pg.mjs path/to/stock_db.sql\n`
  );
  process.exit(1);
}

const raw = readFileSync(input, "utf8");
const lines = raw.split(/\r?\n/);

/** Collect complete INSERT statements (they may span many lines). */
const statements = [];
let buffer = null;

for (const line of lines) {
  if (buffer === null) {
    if (/^\s*INSERT\s+INTO/i.test(line)) {
      buffer = line;
      if (/;\s*$/.test(line.trim())) {
        statements.push(buffer);
        buffer = null;
      }
    }
    // ignore everything else (DDL, comments, functions, views, locks, etc.)
  } else {
    buffer += "\n" + line;
    if (/;\s*$/.test(line.trim())) {
      statements.push(buffer);
      buffer = null;
    }
  }
}
if (buffer !== null) statements.push(buffer); // unterminated tail, best-effort

const touchedTables = new Set();

/** Convert backticks to double quotes ONLY outside single-quoted string literals. */
function convertStatement(stmt) {
  let out = "";
  let inStr = false;
  for (let i = 0; i < stmt.length; i++) {
    const ch = stmt[i];
    const next = stmt[i + 1];

    if (inStr) {
      // handle MySQL backslash escapes inside a string literal
      if (ch === "\\") {
        const e = next;
        if (e === "'") { out += "''"; i++; continue; }
        if (e === "\\") { out += "\\"; i++; continue; }
        if (e === '"') { out += '"'; i++; continue; }
        if (e === "n") { out += "\n"; i++; continue; }
        if (e === "r") { out += "\r"; i++; continue; }
        if (e === "t") { out += "\t"; i++; continue; }
        if (e === "0") { out += ""; i++; continue; } // NUL -> drop
        if (e === "Z") { out += ""; i++; continue; }
        out += e ?? ""; i++; continue; // unknown escape -> literal char
      }
      if (ch === "'") {
        // doubled '' is an escaped quote -> stays inside string
        if (next === "'") { out += "''"; i++; continue; }
        inStr = false;
        out += ch;
        continue;
      }
      out += ch;
    } else {
      if (ch === "'") { inStr = true; out += ch; continue; }
      if (ch === "`") { out += '"'; continue; } // identifier quote
      out += ch;
    }
  }
  return out;
}

const converted = [];
for (const stmt of statements) {
  let s = convertStatement(stmt);

  // record table name for sequence fixup:  INSERT INTO "table" (...)
  const m = s.match(/INSERT\s+INTO\s+"?([a-zA-Z0-9_]+)"?/i);
  if (m) touchedTables.add(m[1]);

  // zero-dates -> NULL
  s = s.replace(/'0000-00-00'/g, "NULL");
  s = s.replace(/'0000-00-00 00:00:00'/g, "NULL");

  converted.push(s.trim());
}

const seqFix = [...touchedTables]
  .map(
    (t) =>
      `DO $$ BEGIN\n  PERFORM setval(pg_get_serial_sequence('"${t}"','id'), GREATEST(COALESCE((SELECT MAX(id) FROM "${t}"),0),1));\nEXCEPTION WHEN others THEN NULL;\nEND $$;`
  )
  .join("\n");

const header = `-- Generated by scripts/mysql-to-pg.mjs
-- Data-only load for PostgreSQL. Run AFTER creating the schema (npm run db:push).
SET client_min_messages = warning;
BEGIN;
SET session_replication_role = replica;  -- skip FK/trigger checks during bulk load
`;

const footer = `
-- Reset identity sequences so future inserts don't collide with loaded ids
${seqFix}

SET session_replication_role = origin;
COMMIT;
`;

writeFileSync(output, header + "\n" + converted.join("\n") + "\n" + footer, "utf8");

console.log(
  `✔ Converted ${statements.length} INSERT statements across ${touchedTables.size} tables.\n` +
    `  Wrote: ${output}\n` +
    `  Next:  npm run db:push   (create schema)\n` +
    `         npm run db:load   (load ${output})`
);
